# French Main Navigation Menu
# ==============================================================================

[[main]]
  name = 'Accueil'
  pageRef = '/'
  weight = 10

[[main]]
  name = 'Podcasts'
  pageRef = '/podcasts'
  weight = 20

[[main]]
  name = 'Contact'
  pageRef = '/contact'
  weight = 30


# Footer Menu
# ------------------------------------------------------------------------------

[[footer]]
  name = 'Accueil'
  pageRef = '/'
  weight = 10

[[footer]]
  name = 'Podcasts'
  pageRef = '/podcasts'
  weight = 20

[[footer]]
  name = 'Contact'
  pageRef = '/contact'
  weight = 30

[[footer]]
  name = 'Mentions l√©gales'
  pageRef = '/legal'
  weight = 40

