# English Main Navigation Menu
# ==============================================================================

[[main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[main]]
  name = 'Podcasts'
  pageRef = '/podcasts'
  weight = 20

[[main]]
  name = 'Contact'
  pageRef = '/contact'
  weight = 30



# Footer Menu
# ------------------------------------------------------------------------------
[[footer]]
  name = 'Privacy Policy'
  pageRef = '/privacy'
  weight = 10

[[footer]]
  name = 'Terms of Service'
  pageRef = '/terms'
  weight = 20
